### PR TITLE
Set DOTNET_INSTALL_DIR

### PR DESCRIPTION
**Pull request by martincostello**
Try setting `DOTNET_INSTALL_DIR` as a workaround to .NET SDK issue.

### CODE REVIEW

**Comment by baronfel** [comment]
It looks like you set the installation directory to the existing location with this change - can you use a completely independent location?

**Comment by martincostello** [comment]
Do you mean for me to point at _anywhere_ that .NET isn't, or is it that you want actions/setup-dotnet to put the version it installs somewhere completely different to the default?

**Comment by baronfel** [comment]
The latter - I want to see if the error recreates with an entirely hermetic dotnet install, which actions/setup-dotnet doesn't do by default (it installs over a set of globally-installed SDKs). Since the only knob we have here is the install directory env var, then setting that to anything other than PROGRAM_FILES/dotnet should be enough to validate this thought.

**Comment by baronfel** [comment]
That's huge, a great validation of one of our hypotheses - I'm chatting with the team about next steps here

**Pull request closed without merging**
